# See: https://github.com/typescript-eslint/typescript-eslint/blob/main/docs/linting/README.md#configuration

extends:
  - airbnb-typescript/base
  - prettier
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/recommended'
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./tsconfig.eslint.json"
rules:
  max-len:
    - error
    - code: 180
  no-console: "off"
  no-underscore-dangle: "off"
  "@typescript-eslint/no-use-before-define": "off"
root: true
