[[IgnoredVulns]]
id = "GHSA-8gh8-hqwg-xf34"
reason = "This is a test dependency"

[[IgnoredVulns]]
id = "GHSA-fjxv-7rqg-78g4"
reason = "This is a test dependency"

[[IgnoredVulns]]
id = "GHSA-p8p7-x288-28g6"
reason = "This is a test dependency"

[[IgnoredVulns]]
id = "GHSA-72xf-g2v4-qvf3"
reason = "This is a test dependency"