name: Check TypeScript

env:
  # See: https://github.com/actions/setup-node/#readme
  NODE_VERSION: 20.x

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-typescript-task.ya?ml"
      - ".eslintignore"
      - "**/.eslintrc*"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.eslint.json"
      - "tsconfig.json"
      - "**.[jt]sx?"
  pull_request:
    paths:
      - ".github/workflows/check-typescript-task.ya?ml"
      - ".eslintignore"
      - "**/.eslintrc*"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.eslint.json"
      - "tsconfig.json"
      - "**.[jt]sx?"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@e26d8975574116b0097a1161e0fe16ba75d84c1c # v1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Lint
        run: task ts:lint
