name: Check TypeScript

env:
  # See: https://github.com/actions/setup-node/#readme
  NODE_VERSION: 24.x

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-typescript-task.ya?ml"
      - ".eslintignore"
      - "**/.eslintrc*"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.eslint.json"
      - "tsconfig.json"
      - "**.[jt]sx?"
  pull_request:
    paths:
      - ".github/workflows/check-typescript-task.ya?ml"
      - ".eslintignore"
      - "**/.eslintrc*"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.eslint.json"
      - "tsconfig.json"
      - "**.[jt]sx?"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@c0bc642852239c2689f73f4ea6459c29405f3c52 # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Lint
        run: task ts:lint
