name: Check Packaging

env:
  # See: https://github.com/actions/setup-node/#readme
  NODE_VERSION: 20.x

on:
  push:
    paths:
      - ".github/workflows/check-packaging-ncc-typescript-task.ya?ml"
      - "lerna.json"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.json"
      - "**.[jt]sx?"
  pull_request:
    paths:
      - ".github/workflows/check-packaging-ncc-typescript-task.ya?ml"
      - "lerna.json"
      - "package.json"
      - "package-lock.json"
      - "Taskfile.ya?ml"
      - "tsconfig.json"
      - "**.[jt]sx?"
  workflow_dispatch:

permissions: {}

jobs:
  check-packaging:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@e26d8975574116b0097a1161e0fe16ba75d84c1c # v1.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Build project
        run: task ts:build

      - name: Check packaging
        # Ignoring CR because ncc's output has a mixture of line endings, while the repository should only contain
        # Unix-style EOL.
        run: git diff --ignore-cr-at-eol --color --exit-code dist
